---
title: "Analiza Sklepu Rowerowego"
author: "Jagoda Chęcińska, Piotr Łukowski, Tomasz Kotliński"
date: "`r Sys.Date()`"
output: html_document
---

# Piraci-z-Zatoki: Analiza Sklepu Rowerowego

## Wstęp

Klienci sklepu rowerowego wzięli udział w ankiecie, w której dostarczyli szczegółowe informacje na swój temat, takie jak: status cywilny, płeć, poziom dochodów, liczba dzieci, poziom wykształcenia, wykonywany zawód, status posiadania domu, liczba samochodów, odległość do miejsca pracy, region zamieszkania oraz wiek. 

Celem analizy jest określenie, które z tych czynników mają największy wpływ na decyzję o zakupie roweru.

## Przygotowanie danych

### Załadowanie pakietów

```{
# Instalacja i załadowanie wymaganych pakietów
install.packages(c("readr", "naniar", "dplyr", "summarytools", "tidyr", 
                   "car", "psych", "ggplot2", "mice", "rpart", 
                   "ggcorrplot", "rpart.plot", "gridExtra", "factoextra", "plyr"))

library(readr)
library(naniar)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(mice)
library(rpart)
library(ggcorrplot)
library(rpart.plot)
library(factoextra)
library(gridExtra)
library(car)
library(psych)
library(summarytools)

